-- Final Scene

blue_mat = gr.material({0, 0, 1}, {0.5, 0.7, 0.5}, 25)
black_mat = gr.material({0, 0, 0}, {0.5, 0.7, 0.5}, 25)
white_mat = gr.material({1, 1, 1}, {0.5, 0.7, 0.5}, 25)
red_mat = gr.material({1, 0, 0}, {0.5, 0.7, 0.5}, 25)
cornsilk_mat = gr.material({1.0, 0.97, 0.86}, {0.5, 0.7, 0.5}, 25)
glass_mat = gr.transparent_material(1.0, 0, 1.5);
globe_mat = gr.transparent_material(1.0, 0, 1.2);
mirror_mat = gr.transparent_material(0, 1.0, 1.2);

desk_top_mat = gr.cube_texture('Assets/desk_top.png', 25)
mac_screen_mat = gr.cube_texture('Assets/mac_screen.png', 75)
mac_board_mat = gr.cube_texture('Assets/mac_board.png', 25)
paper_mat_1 = gr.cube_texture('Assets/paper_1.png', 25)
frame_mat = gr.cube_texture('Assets/picture_frame.png', 25)
geese_mat = gr.cube_texture('Assets/geese.png', 25)
floor_mat = gr.cube_texture('Assets/floor.png', 50)
wall_mat = gr.cube_texture('Assets/wall4.png', 50)
basketball_mat = gr.sphere_texture('Assets/basketball_texture.png', 10)

scene = gr.node( 'scene' )

-- Desk
desk_top = gr.cube('desk_top')
desk_top:set_material(desk_top_mat)
desk_top:scale(2.5, 0.15, 1.5)

desk_leg = gr.cylinder('desk_leg')
desk_leg:set_material(cornsilk_mat)
desk_leg:scale(0.1, 0.8, 0.1)

desk_leg_tl = gr.node('desk_leg_tl')
desk_leg_tl:add_child(desk_leg)
desk_leg_tl:translate(-1.25 + 0.2, -0.8, -0.75 + 0.2)

desk_leg_tr = gr.node('desk_leg_tr')
desk_leg_tr:add_child(desk_leg)
desk_leg_tr:translate(1.25 - 0.2, -0.8, -0.75 + 0.2)

desk_leg_bl = gr.node('desk_leg_lr')
desk_leg_bl:add_child(desk_leg)
desk_leg_bl:translate(-1.25 + 0.2, -0.8, 0.75 - 0.2)

desk_leg_br = gr.node('desk_leg_tr')
desk_leg_br:add_child(desk_leg)
desk_leg_br:translate(1.25 - 0.2, -0.8, 0.75 - 0.2)

desk = gr.union('desk')
desk:scale(2, 2, 2)
desk:add_child(desk_top)
desk:add_child(desk_leg_tl)
desk:add_child(desk_leg_tr)
desk:add_child(desk_leg_bl)
desk:add_child(desk_leg_br)

-- Mac
mac_screen = gr.cube('mac_screen')
mac_screen:set_material(mac_screen_mat)
mac_screen:scale(1.2, 1.0, 0.05)
mac_screen:rotate('X', -5)

mac_board = gr.cube('mac_board')
mac_board:set_material(mac_board_mat)
mac_board:scale(1.2, 0.05, 1.0)
mac_board:translate(0, -0.5, 0.6)

mac = gr.union('mac')
mac:add_child(mac_screen)
mac:add_child(mac_board)
mac:translate(-0.25, 0.7, -0.75)

-- Glasses
glass_frame = gr.sphere('glass_frame')
glass_frame:set_material(black_mat)
glass_frame:scale(1, 1, 0.05)

glass_lens = gr.sphere('glass_lens')
glass_lens:set_material(glass_mat)
glass_lens:scale(0.95, 0.95, 0.1)

glass_frame_left = gr.node('glass_frame_left')
glass_frame_left:add_child(glass_frame)
glass_frame_left:add_child(glass_lens)
glass_frame_left:translate(-1.24, 0, 0)
glass_frame_right = gr.node('glass_frame_right')
glass_frame_right:add_child(glass_frame)
glass_frame_right:add_child(glass_lens)
glass_frame_right:translate(1.24, 0, 0)
glass_frame_joiner = gr.cube('glass_frame_joiner')
glass_frame_joiner:set_material(black_mat)
glass_frame_joiner:scale(0.5, 0.2, 0.05)

glass_bar_front = gr.cube('glass_bar_front')
glass_bar_front:set_material(black_mat)
glass_bar_front:scale(0.05, 0.2, 2)
glass_bar_back = gr.cube('glass_bar_back')
glass_bar_back:set_material(black_mat)
glass_bar_back:scale(0.05, 0.2, 1)
glass_bar_back:rotate('X', -40)
glass_bar_back:translate(0, -0.3, -1.3)

glass_bar_left = gr.node('glass_bar_left')
glass_bar_left:add_child(glass_bar_front)
glass_bar_left:add_child(glass_bar_back)
glass_bar_left:translate(-2.24, 0, -1)
glass_bar_right = gr.node('glass_bar_right')
glass_bar_right:add_child(glass_bar_front)
glass_bar_right:add_child(glass_bar_back)
glass_bar_right:translate(2.24, 0, -1)

glasses = gr.union('glasses')
glasses:add_child(glass_frame_left)
glasses:add_child(glass_frame_right)
glasses:add_child(glass_frame_joiner)
glasses:add_child(glass_bar_left)
glasses:add_child(glass_bar_right)

glasses:scale(0.15, 0.15, 0.15)
glasses:rotate('Y', -35)
glasses:translate(1, 0.35, -0.2)

-- papers
paper_1 = gr.cube('paper_1')
paper_1:set_material(paper_mat_1)
paper_1:scale(1, 0.01, 1.5)
paper_1:translate(1, 0.2, 0)

-- dice
dice_intersect = gr.intersect('dice_intersect')

dice_body_1 = gr.cube('dice_body_1')
dice_body_1:set_material(white_mat)

dice_body_2 = gr.sphere('dice_body_2')
dice_body_2:set_material(white_mat)
dice_body_2:scale(0.7, 0.7, 0.7)
dice_intersect:add_child(dice_body_1)
dice_intersect:add_child(dice_body_2)

dice_dot_red = gr.sphere('dice_dot_red')
dice_dot_red:set_material(red_mat)
dice_dot_red:scale(0.1, 0.1, 0.1)

dice_dot_black = gr.sphere('dice_dot_black')
dice_dot_black:set_material(black_mat)
dice_dot_black:scale(0.1, 0.1, 0.1)

dice = gr.difference('dice_difference')

dice_dot_1_1 = gr.node('dice_dot_1_1')
dice_dot_1_1:add_child(dice_dot_red)
dice_dot_1_1:translate(0, 0, 0.525)
dice_dot_2_1 = gr.node('dice_dot_2_1')
dice_dot_2_1:add_child(dice_dot_black)
dice_dot_2_1:translate(-0.525, 0.225, 0)
dice_dot_2_1:rotate('X', 45)
dice_dot_2_2 = gr.node('dice_dot_2_2')
dice_dot_2_2:add_child(dice_dot_black)
dice_dot_2_2:translate(-0.525, -0.225, 0)
dice_dot_2_2:rotate('X', 45)
dice_dot_3_1 = gr.node('dice_dot_3_1')
dice_dot_3_1:add_child(dice_dot_black)
dice_dot_3_1:translate(0.525, 0.225, 0)
dice_dot_3_1:rotate('X', 45)
dice_dot_3_2 = gr.node('dice_dot_3_2')
dice_dot_3_2:add_child(dice_dot_black)
dice_dot_3_2:translate(0.525, 0, 0)
dice_dot_3_2:rotate('X', 45)
dice_dot_3_3 = gr.node('dice_dot_3_3')
dice_dot_3_3:add_child(dice_dot_black)
dice_dot_3_3:translate(0.525, -0.225, 0)
dice_dot_3_3:rotate('X', 45)
dice_dot_4_1 = gr.node('dice_dot_4_1')
dice_dot_4_1:add_child(dice_dot_black)
dice_dot_4_1:translate(-0.2, 0.525, -0.2)
dice_dot_4_2 = gr.node('dice_dot_4_2')
dice_dot_4_2:add_child(dice_dot_black)
dice_dot_4_2:translate(-0.2, 0.525, 0.2)
dice_dot_4_3 = gr.node('dice_dot_4_3')
dice_dot_4_3:add_child(dice_dot_black)
dice_dot_4_3:translate(0.2, 0.525, -0.2)
dice_dot_4_4 = gr.node('dice_dot_4_4')
dice_dot_4_4:add_child(dice_dot_black)
dice_dot_4_4:translate(0.2, 0.525, 0.2)
dice_dot_5_1 = gr.node('dice_dot_5_1')
dice_dot_5_1:add_child(dice_dot_black)
dice_dot_5_1:translate(-0.2, -0.525, -0.2)
dice_dot_5_2 = gr.node('dice_dot_5_2')
dice_dot_5_2:add_child(dice_dot_black)
dice_dot_5_2:translate(-0.2, -0.525, 0.2)
dice_dot_5_3 = gr.node('dice_dot_5_3')
dice_dot_5_3:add_child(dice_dot_black)
dice_dot_5_3:translate(0.2, -0.525, -0.2)
dice_dot_5_4 = gr.node('dice_dot_5_4')
dice_dot_5_4:add_child(dice_dot_black)
dice_dot_5_4:translate(0.2, -0.525, 0.2)
dice_dot_5_5 = gr.node('dice_dot_5_5')
dice_dot_5_5:add_child(dice_dot_black)
dice_dot_5_5:translate(0, -0.525, 0)
dice_dot_6_1 = gr.node('dice_dot_6_1')
dice_dot_6_1:add_child(dice_dot_black)
dice_dot_6_1:translate(-0.2, -0.2, -0.525)
dice_dot_6_2 = gr.node('dice_dot_6_2')
dice_dot_6_2:add_child(dice_dot_black)
dice_dot_6_2:translate(-0.2, 0, -0.525)
dice_dot_6_3 = gr.node('dice_dot_6_3')
dice_dot_6_3:add_child(dice_dot_black)
dice_dot_6_3:translate(-0.2, 0.2, -0.525)
dice_dot_6_4 = gr.node('dice_dot_6_4')
dice_dot_6_4:add_child(dice_dot_black)
dice_dot_6_4:translate(0.2, -0.2, -0.525)
dice_dot_6_5 = gr.node('dice_dot_6_5')
dice_dot_6_5:add_child(dice_dot_black)
dice_dot_6_5:translate(0.2, 0, -0.525)
dice_dot_6_6 = gr.node('dice_dot_6_6')
dice_dot_6_6:add_child(dice_dot_black)
dice_dot_6_6:translate(0.2, 0.2, -0.525)

dice:add_child(dice_intersect)
dice:add_child(dice_dot_1_1)
dice:add_child(dice_dot_2_1)
dice:add_child(dice_dot_2_2)
dice:add_child(dice_dot_3_1)
dice:add_child(dice_dot_3_2)
dice:add_child(dice_dot_3_3)
dice:add_child(dice_dot_4_1)
dice:add_child(dice_dot_4_2)
dice:add_child(dice_dot_4_3)
dice:add_child(dice_dot_4_4)
dice:add_child(dice_dot_5_1)
dice:add_child(dice_dot_5_2)
dice:add_child(dice_dot_5_3)
dice:add_child(dice_dot_5_4)
dice:add_child(dice_dot_5_5)
dice:add_child(dice_dot_6_1)
dice:add_child(dice_dot_6_2)
dice:add_child(dice_dot_6_3)
dice:add_child(dice_dot_6_4)
dice:add_child(dice_dot_6_5)
dice:add_child(dice_dot_6_6)

dice:scale(0.25, 0.25, 0.25)

dice_1 = gr.node('dice_1')
dice_1:add_child(dice)
dice_1:rotate('Y', 45)
dice_1:translate(-1.5, 0.3, 0)

dice_2 = gr.node('dice_2')
dice_2:add_child(dice)
dice_2:rotate('Y', -30)
dice_2:rotate('X', 180)
dice_2:translate(-1.75, 0.3, 0.2)

-- Transparent sphere
glass_ball = gr.sphere('glass_ball')
glass_ball:set_material(glass_mat)
glass_ball:scale(0.2, 0.2, 0.2)
glass_ball:translate(-1.6, 0.5, 0.55)

-- snow globe
globe_base = gr.difference('globe_base')
globe_base_1 = gr.cone('globe_base_1')
globe_base_1:set_material(white_mat)
globe_base_2 = gr.cube('globe_base_2')
globe_base_2:set_material(white_mat)
globe_base_2:scale(2, 2, 2)
globe_base_2:translate(0, 0.5, 0)
globe_base:add_child(globe_base_1)
globe_base:add_child(globe_base_2)

globe_ball = gr.sphere('globe_ball')
globe_ball:set_material(globe_mat)
globe_ball:translate(0, 0.25, 0)

-- globe_content = gr.union('globe_content')

-- globe_cone = gr.cone('globe_cone')
-- globe_cone:set_material(blue_mat)
-- globe_cone:translate(1, 0, 0)
-- globe_cylinder = gr.cylinder('globe_cylinder')
-- globe_cylinder:set_material(blue_mat)
-- globe_cylinder:translate(-1, 0, 0)

-- globe_content:add_child(globe_cone)
-- globe_content:add_child(globe_cylinder)
-- globe_content:scale(0.3, 0.3, 0.3)
-- globe_content:translate(-0.1, 0, 0.2)

globe_shell = gr.union('globe_shell')
globe_shell:add_child(globe_ball)
globe_shell:add_child(globe_base)

globe = gr.node('globe')
globe:add_child(globe_shell)
-- globe:add_child(globe_content)
globe:scale(0.4, 0.4, 0.4)
globe:translate(-1.9, 0.6, 0.7)

-- picture frame
picture_frame = gr.difference('picture_frame')
picture_frame_border = gr.cube('picture_frame_border')
picture_frame_border:set_material(frame_mat)
picture_frame_border:scale(1, 1.5, 0.1)
picture_frame_center = gr.cube('picture_frame_center')
picture_frame_center:set_material(black_mat)
picture_frame_center:scale(0.8, 1.2, 0.2)
picture_frame:add_child(picture_frame_border)
picture_frame:add_child(picture_frame_center)

picture_content = gr.cube('picture_content')
picture_content:set_material(geese_mat)
picture_content:scale(0.8, 1.2, 0.1)

picture_front = gr.union('picture_front')
picture_front:add_child(picture_frame)
picture_front:add_child(picture_content)
picture_front:rotate('X', -15)

picture_holder = gr.cube('picture_holder')
picture_holder:set_material(white_mat)
picture_holder:scale(0.8, 1, 0.05)
picture_holder:rotate('X', 25)
picture_holder:translate(0, -0.275, -0.25)

picture = gr.node('picture')
picture:add_child(picture_front)
picture:add_child(picture_holder)

picture:scale(0.5, 0.5, 0.5)
picture:rotate('Y', 35)
picture:translate(-1.5, 0.5, -0.5)

-- mirror
mirror_frame = gr.difference('mirror_frame')
mirror_frame_border = gr.cube('mirror_frame_border')
mirror_frame_border:set_material(white_mat)
mirror_frame_border:scale(1, 1.5, 0.1)
mirror_frame_center = gr.cube('mirror_frame_center')
mirror_frame_center:set_material(white_mat)
mirror_frame_center:scale(0.8, 1.2, 0.2)
mirror_frame:add_child(mirror_frame_border)
mirror_frame:add_child(mirror_frame_center)

mirror_content = gr.cube('mirror_content')
mirror_content:set_material(mirror_mat)
mirror_content:scale(0.8, 1.2, 0.1)

mirror = gr.union('mirror')
mirror:add_child(mirror_frame)
mirror:add_child(mirror_content)
mirror:rotate('X', 15)
mirror:rotate('Y', 90)
mirror:scale(0.8, 0.8, 0.8)
mirror:translate(2.2, 0.75, 0.4)

-- Wall
wall_back = gr.cube('wall_back')
wall_back:set_material(wall_mat)
wall_back:scale(7.5, 7.5, 0.5)
wall_back:translate(0, 0, -1.5)
wall_right = gr.cube('wall_right')
wall_right:set_material(wall_mat)
wall_right:scale(0.5, 7.5, 7.5)
wall_right:translate(2.7, 0, 0)
floor = gr.cube('floor')
floor:set_material(floor_mat)
floor:scale(7.5, 0.5, 7.5)
floor:translate(0, -3.5, 0)

-- Basketball
basketball = gr.sphere('basketball')
basketball:set_material(basketball_mat)
basketball:scale(0.4, 0.4, 0.4)
basketball:rotate('Z', 90)
basketball:translate(0.8, -2.8, 1.2)

scene:add_child(desk)
scene:add_child(mac)
scene:add_child(glasses)
scene:add_child(paper_1)
scene:add_child(dice_1)
scene:add_child(dice_2)
scene:add_child(globe)
scene:add_child(picture)
scene:add_child(mirror)
scene:add_child(wall_back)
scene:add_child(wall_right)
scene:add_child(floor)
scene:add_child(basketball)

scene:rotate('Y', 35)
scene:rotate('X', 45)
scene:translate(0, 0, -5)

white_light_1 = gr.light({0, 7.07107, 7.07107}, {0.75, 0.75, 0.75}, {1, 0, 0})
white_light_2 = gr.light({5.73576, -5.79228, 5.79228}, {0.75, 0.75, 0.75}, {1, 0, 0})
gr.render(scene, 'results/final.png', 256, 256,
    {0, 0, 0}, {0, 0, -1}, {0, 1, 0}, 50,
    {0.2, 0.2, 0.2}, {white_light_1, white_light_2}, 
    -- focal dist
    -15, 
    -- camera radius (0 for point)
    0, 
    -- camera sample rate (0 for infinite loop)
    0.2,
    -- anti aliasing sample radius (0 for no sample)
    0.5,
    -- anti aliasing sample rate (0 for infinite loop)
    0.5)
